"""Generate the Homebrew formula from what is actually on PyPI.

    python packaging/brew_formula.py 0.1.0 > Formula/fleetwright.rb

Generated rather than hand-maintained, and generated from **PyPI rather than
from the repo**, for one reason: a formula names a tarball and its sha256. If
those are typed by a human they are typed from a build that may not be the one
that was published, and the failure mode is `brew install` downloading a file
whose checksum does not match — days later, for someone else.

Zero runtime dependencies is what makes this file twenty lines instead of two
hundred. A formula for a package with dependencies needs a `resource` block per
transitive dependency, each with its own url and sha256, each of which goes
stale independently. There are none here, so there is nothing to go stale.
"""

from __future__ import annotations

import hashlib
import json
import sys
import urllib.request

TEMPLATE = '''# Generated by packaging/brew_formula.py. Do not edit by hand.
class Fleetwright < Formula
  include Language::Python::Virtualenv

  desc "{desc}"
  homepage "https://github.com/narimannemo/fleetwright"
  url "{url}"
  sha256 "{sha256}"
  license "Apache-2.0"

  depends_on "python@3.13"

  # No resource blocks: fleetwright has no runtime dependencies. That is the
  # whole reason this formula is short, and it is worth keeping that way.
  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "fleetwright {version}", shell_output("#{{bin}}/fleetwright --version")

    # The demo runs a real fleet against a temporary database: three workers
    # claiming without collision, a crash, and a reclaim. If the install is
    # broken in any way that matters, this is where it shows.
    assert_match "nobody got the same page", shell_output("#{{bin}}/fleetwright demo")

    # And one round trip through the actual store, in the sandbox.
    system bin/"fleetwright", "add", "t", "u1", "--db", "t.db"
    assert_match "u1", shell_output("#{{bin}}/fleetwright claim t --db t.db")
  end
end
'''


def sdist(version: str) -> tuple[str, str, str]:
    """The published sdist's url, sha256 and summary — from PyPI, not locally."""
    with urllib.request.urlopen(
            f"https://pypi.org/pypi/fleetwright/{version}/json", timeout=30) as fh:
        data = json.load(fh)
    for f in data["urls"]:
        if f["packagetype"] == "sdist":
            sha = f["digests"].get("sha256")
            if not sha:
                # Never trust a missing digest: download and compute rather
                # than emitting a formula with a blank checksum.
                with urllib.request.urlopen(f["url"], timeout=120) as dl:
                    sha = hashlib.sha256(dl.read()).hexdigest()
            return f["url"], sha, data["info"]["summary"]
    raise SystemExit(f"no sdist published for fleetwright {version}")


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    version = sys.argv[1].lstrip("v")
    url, sha, summary = sdist(version)
    # Homebrew audits reject a desc that is too long, starts with the formula
    # name, or ends in a full stop. Trim rather than let `brew audit` fail in
    # someone else's CI.
    desc = summary.split(".")[0].strip()
    if desc.lower().startswith("fleetwright"):
        desc = desc[len("fleetwright"):].lstrip(" -:")
    if len(desc) > 70:
        # At a word boundary. `brew audit` only checks the length, but a desc
        # cut mid-word ("divides a job lis") is what people actually see in
        # `brew info`, and it reads as a broken package.
        desc = desc[:70].rsplit(" ", 1)[0]
    desc = desc.rstrip(" ,")
    print(TEMPLATE.format(desc=desc, url=url, sha256=sha, version=version), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
